[build]
  command = "cd frontEnd && npm ci && npm run build"
  publish = "frontEnd/dist"

[build.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200